disabled_rules:
  - identifier_name

excluded:
  - .build
  - Tests

line_length:
  warning: 140
  error: 200

file_length:
  warning: 600
  error: 1000

type_body_length:
  warning: 500
  error: 700

function_body_length:
  warning: 100
  error: 120

cyclomatic_complexity:
  warning: 15
  error: 18

# Allow longer parameter lists for configuration
function_parameter_count:
  warning: 8
  error: 12

# Allow some nesting for configuration structures
nesting:
  type_level:
    warning: 2
    error: 3

# Require trailing commas in multi-line collections (common Swift style)
trailing_comma:
  mandatory_comma: true
