version: "1.0"

calendar_pair:
  name: "Work to Personal Sync"
  source:
    account: "work@company.com"
    calendar: "Work Calendar" # Use exact name from --verbose output
  destination:
    account: "personal@gmail.com"
    calendar: "Personal Calendar" # Use exact name from --verbose output
  title_template: "1:1 with {{otherPerson}}"
  # IMPORTANT: Set your actual email address for accurate 1:1 detection
  # Use the email that appears in your meeting attendees
  # Run with --verbose to see all organizer emails in your calendar
  owner_email: "john.doe@company.com"

sync_window:
  weeks: 3
  start_offset: 0

filters:
  exclude_all_day: true
  exclude_keywords:
    - "standup"
    - "daily scrum"
    - "team meeting"
    - "all-hands"
    - "retrospective"
    - "planning"
    - "review"
  exclude_private: true

logging:
  level: "info"
  colored_output: true
# DEBUGGING TIPS:
#
# 1. First run: calsync1on1 --verbose --dry-run
#    This shows all available calendars and debugging info
#
# 2. If no 1:1 meetings found:
#    - Check the "owner_email" matches your email in meeting attendees
#    - Look for "events with 2 attendees NOT detected as 1:1" in output
#    - Verify calendar names exactly match available calendars list
#
# 3. If events are filtered out:
#    - Set exclude_all_day: false
#    - Remove keywords that might match your meetings
#    - Set exclude_private: false
#
# 4. For troubleshooting, use this minimal config:
#    - Set weeks: 4 and start_offset: -1 for wider date range
#    - Disable all filters temporarily
#    - Run --verbose to see detailed event analysis
