#!/usr/bin/env bash
set -euo pipefail

# Usage: scripts/generate_build_info.sh <module-name>

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${PROJECT_ROOT}"

MODULE_NAME="CalSync1on1"

if [[ ! -f VERSION ]]; then
  echo "VERSION file not found in project root." >&2
  exit 1
fi

VERSION_STR="$(tr -d ' \n' < VERSION)"
GIT_SHA="$(git rev-parse --short HEAD)"
BUILD_DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

OUT_DIR="Sources/${MODULE_NAME}"
OUT_FILE="${OUT_DIR}/BuildInfo.swift"

cat > "${OUT_FILE}" <<EOF
// This file is generated by generate_build_info.sh. Do not edit manually.

public enum BuildInfo {
    public static let version: String = "${VERSION_STR}"
    public static let gitSHA: String = "${GIT_SHA}"
    public static let buildDateUTC: String = "${BUILD_DATE}"
    public static let composite: String = "\(version) (\(gitSHA)) built \(buildDateUTC)"
}
EOF

echo "Generated ${OUT_FILE}"
